version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'nginx:latest'
    volumes:
      - ./:/srv
    ports:
      - "8444:8444"
    environment:
      - env=dev
    container_name: nginx
